export const kotlinDeclarationsSize = {
    "kotlin.collections.Iterable" : 38,
    "kotlin.text.Appendable" : 26,
    "kotlin.text.checkRadix(Int)" : 809,
    "kotlin.text.StringBuilder" : 2955,
    "kotlin.text.StringBuilder.<init>(CharArray)" : 141,
    "kotlin.text.StringBuilder.array" : 29,
    "kotlin.text.StringBuilder.<init>()" : 58,
    "kotlin.text.StringBuilder.<init>(Int)" : 92,
    "kotlin.text.StringBuilder.<set-_length>(Int)" : 127,
    "kotlin.text.StringBuilder._length" : 25,
    "kotlin.text.StringBuilder.<get-length>()" : 149,
    "kotlin.text.StringBuilder.append(Any?)" : 93,
    "kotlin.text.StringBuilder.append(Int)" : 371,
    "kotlin.text.StringBuilder.append(Long)" : 111,
    "kotlin.text.StringBuilder.append(String?)" : 574,
    "kotlin.text.StringBuilder.ensureCapacity(Int)" : 609,
    "kotlin.text.StringBuilder.toString()" : 221,
    "kotlin.text.StringBuilder.ensureExtraCapacity(Int)" : 139,
    "kotlin.text.insertString(CharArray, Int, String)" : 199,
    "kotlin.CharSequence" : 64,
    "kotlin.CharSequence.<get-length>()" : 34,
    "kotlin.Comparable" : 89,
    "kotlin.Comparable.compareTo(T)" : 48,
    "kotlin.Number" : 150,
    "kotlin.Number.<init>()" : 67,
    "kotlin.Number.toString()" : 44,
    "kotlin.Function" : 38,
    "kotlin.Unit" : 196,
    "kotlin.Unit.<init>()" : 101,
    "kotlin.Unit.toString()" : 60,
    "kotlin.Unit_instance" : 44,
    "kotlin.Unit_getInstance()" : 191,
    "kotlin.collections.<get-lastIndex>()" : 107,
    "kotlin.ranges.until(Int)" : 460,
    "kotlin.ranges.coerceAtMost(Int)" : 153,
    "kotlin.ranges.contains(Long)" : 626,
    "kotlin.ranges.toIntExactOrNull()" : 397,
    "kotlin.collections.Companion" : 2294,
    "kotlin.collections.Companion.<init>()" : 106,
    "kotlin.collections.Companion.checkRangeIndexes(Int, Int, Int)" : 975,
    "kotlin.collections.Companion.checkBoundsIndexes(Int, Int, Int)" : 990,
    "kotlin.collections.Companion.toString()" : 44,
    "kotlin.collections.Companion_instance" : 54,
    "kotlin.collections.Companion_getInstance()" : 180,
    "kotlin.internal.getProgressionLastElement(Int, Int, Int)" : 708,
    "kotlin.internal.differenceModulo(Int, Int, Int)" : 158,
    "kotlin.internal.mod(Int, Int)" : 207,
    "kotlin.internal.getProgressionLastElement(Long, Long, Long)" : 768,
    "kotlin.internal.differenceModulo(Long, Long, Long)" : 163,
    "kotlin.internal.mod(Long, Long)" : 239,
    "kotlin.random.Default" : 1028,
    "kotlin.random.Default.<init>()" : 159,
    "kotlin.random.Default.defaultRandom" : 52,
    "kotlin.random.Default.nextBits(Int)" : 227,
    "kotlin.random.Default.nextInt()" : 193,
    "kotlin.random.Default.nextInt(Int, Int)" : 240,
    "kotlin.random.Default.toString()" : 44,
    "kotlin.random.Default_instance" : 50,
    "kotlin.random.Default_getInstance()" : 161,
    "kotlin.random.Random" : 2053,
    "kotlin.random.Random.<init>()" : 67,
    "kotlin.random.Random.nextBits(Int)" : 43,
    "kotlin.random.Random.nextInt()" : 141,
    "kotlin.random.Random.nextInt(Int, Int)" : 1583,
    "kotlin.random.Random.toString()" : 44,
    "kotlin.random.checkRangeBounds(Int, Int)" : 746,
    "kotlin.random.fastLog2(Int)" : 119,
    "kotlin.random.boundsErrorMessage(Any, Any)" : 324,
    "kotlin.random.Random(Int)" : 153,
    "kotlin.random.takeUpperBits(Int)" : 346,
    "kotlin.random.XorWowRandom" : 3909,
    "kotlin.random.XorWowRandom.<init>(Int, Int, Int, Int, Int, Int)" : 2080,
    "kotlin.random.XorWowRandom.x" : 19,
    "kotlin.random.XorWowRandom.y" : 19,
    "kotlin.random.XorWowRandom.z" : 19,
    "kotlin.random.XorWowRandom.w" : 19,
    "kotlin.random.XorWowRandom.v" : 19,
    "kotlin.random.XorWowRandom.addend" : 24,
    "kotlin.random.XorWowRandom.<init>(Int, Int)" : 362,
    "kotlin.random.XorWowRandom.nextInt()" : 793,
    "kotlin.random.XorWowRandom.nextBits(Int)" : 192,
    "kotlin.random.XorWowRandom.nextInt(Int, Int)" : 61,
    "kotlin.random.XorWowRandom.toString()" : 44,
    "kotlin.ranges.Companion" : 304,
    "kotlin.ranges.Companion.<init>()" : 164,
    "kotlin.ranges.Companion.EMPTY" : 46,
    "kotlin.ranges.Companion.toString()" : 44,
    "kotlin.ranges.Companion_instance" : 54,
    "kotlin.ranges.Companion_getInstance()" : 171,
    "kotlin.ranges.IntRange" : 1594,
    "kotlin.ranges.IntRange.<init>(Int, Int)" : 159,
    "kotlin.ranges.IntRange.<get-start>()" : 136,
    "kotlin.ranges.IntRange.<get-endInclusive>()" : 142,
    "kotlin.ranges.IntRange.contains(Int)" : 270,
    "kotlin.ranges.IntRange.contains(T)" : 219,
    "kotlin.ranges.IntRange.toString()" : 310,
    "kotlin.ranges.LongRange" : 1617,
    "kotlin.ranges.LongRange.<init>(Long, Long)" : 163,
    "kotlin.ranges.LongRange.<get-start>()" : 139,
    "kotlin.ranges.LongRange.<get-endInclusive>()" : 145,
    "kotlin.ranges.LongRange.contains(Long)" : 273,
    "kotlin.ranges.LongRange.contains(T)" : 221,
    "kotlin.ranges.LongRange.toString()" : 312,
    "kotlin.ranges.IntProgression" : 1969,
    "kotlin.ranges.IntProgression.<init>(Int, Int, Int)" : 659,
    "kotlin.ranges.IntProgression.first" : 41,
    "kotlin.ranges.IntProgression.last" : 40,
    "kotlin.ranges.IntProgression.step" : 40,
    "kotlin.ranges.IntProgression.toString()" : 1034,
    "kotlin.ranges.LongProgression" : 2020,
    "kotlin.ranges.LongProgression.<init>(Long, Long, Long)" : 674,
    "kotlin.ranges.LongProgression.first" : 42,
    "kotlin.ranges.LongProgression.last" : 41,
    "kotlin.ranges.LongProgression.step" : 41,
    "kotlin.ranges.LongProgression.toString()" : 1065,
    "kotlin.ranges.ClosedRange" : 373,
    "kotlin.ranges.ClosedRange.<get-start>()" : 31,
    "kotlin.ranges.ClosedRange.<get-endInclusive>()" : 38,
    "kotlin.ranges.ClosedRange.contains(T)" : 242,
    "kotlin.ranges.OpenEndRange" : 140,
    "kotlin.text.LOWER_CASE_HEX_DIGITS" : 67,
    "kotlin.text.UPPER_CASE_HEX_DIGITS" : 67,
    "kotlin.NotImplementedError" : 248,
    "kotlin.NotImplementedError.<init>(String)" : 101,
    "kotlin.NotImplementedError.<get-message>()" : 50,
    "kotlin.NotImplementedError.toString()" : 44,
    "kotlin.<UInt__<init>-impl>(Int)" : 165,
    "kotlin.<UInt__<get-data>-impl>(UInt)" : 81,
    "kotlin.UInt__compareTo-impl(UInt, UInt)" : 242,
    "kotlin.UInt__toString-impl(UInt)" : 275,
    "kotlin.UInt" : 1061,
    "kotlin.UInt.<init>(Int)" : 130,
    "kotlin.UInt.data" : 40,
    "kotlin.UInt.compareTo(UInt)" : 246,
    "kotlin.UInt.compareTo(T)" : 289,
    "kotlin.UInt.toString()" : 151,
    "kotlin.<ULong__<get-data>-impl>(ULong)" : 84,
    "kotlin.ULong__compareTo-impl(ULong, ULong)" : 248,
    "kotlin.ULong__toString-impl(ULong)" : 120,
    "kotlin.ULong" : 1074,
    "kotlin.ULong.<init>(Long)" : 131,
    "kotlin.ULong.data" : 41,
    "kotlin.ULong.compareTo(ULong)" : 250,
    "kotlin.ULong.compareTo(T)" : 291,
    "kotlin.ULong.toString()" : 154,
    "kotlin.uintCompare(Int, Int)" : 586,
    "kotlin.ulongCompare(Long, Long)" : 613,
    "kotlin.ulongToString(Long)" : 90,
    "kotlin.ulongToString(Long, Int)" : 2039,
    "kotlin.Any" : 1075,
    "kotlin.Any.<init>()" : 118,
    "kotlin.Any.typeInfo" : 26,
    "kotlin.Any._hashCode" : 27,
    "kotlin.Any.toString()" : 814,
    "kotlin.identityHashCode()" : 342,
    "kotlin.Array" : 637,
    "kotlin.Array.<init>(Int)" : 147,
    "kotlin.Array.storage" : 52,
    "kotlin.Array.get(Int)" : 177,
    "kotlin.Array.set(Int, T)" : 154,
    "kotlin.Array.toString()" : 44,
    "kotlin.ShortArray" : 226,
    "kotlin.ShortArray.storage" : 54,
    "kotlin.ShortArray.<init>(WasmShortArray)" : 94,
    "kotlin.ShortArray.toString()" : 44,
    "kotlin.LongArray" : 223,
    "kotlin.LongArray.storage" : 53,
    "kotlin.LongArray.<init>(WasmLongArray)" : 93,
    "kotlin.LongArray.toString()" : 44,
    "kotlin.CharArray" : 488,
    "kotlin.CharArray.<init>(Int)" : 125,
    "kotlin.CharArray.storage" : 53,
    "kotlin.CharArray.set(Int, Char)" : 157,
    "kotlin.CharArray.<get-size>()" : 58,
    "kotlin.CharArray.toString()" : 44,
    "kotlin.Boolean__not-impl(Boolean)" : 153,
    "kotlin.Boolean__toInt-impl(Boolean)" : 113,
    "kotlin.Char__toInt-impl(Char)" : 124,
    "kotlin.Char__toString-impl(Char)" : 318,
    "kotlin.Companion" : 1594,
    "kotlin.Companion.<init>()" : 636,
    "kotlin.Companion.MIN_VALUE" : 62,
    "kotlin.Companion.MAX_VALUE" : 61,
    "kotlin.Companion.MIN_HIGH_SURROGATE" : 58,
    "kotlin.Companion.MAX_HIGH_SURROGATE" : 58,
    "kotlin.Companion.MIN_LOW_SURROGATE" : 57,
    "kotlin.Companion.MAX_LOW_SURROGATE" : 57,
    "kotlin.Companion.MIN_SURROGATE" : 53,
    "kotlin.Companion.MAX_SURROGATE" : 53,
    "kotlin.Companion.MIN_SUPPLEMENTARY_CODE_POINT" : 73,
    "kotlin.Companion.MIN_CODE_POINT" : 55,
    "kotlin.Companion.MAX_CODE_POINT" : 61,
    "kotlin.Companion.MIN_RADIX" : 50,
    "kotlin.Companion.MAX_RADIX" : 51,
    "kotlin.Companion.SIZE_BYTES" : 42,
    "kotlin.Companion.SIZE_BITS" : 42,
    "kotlin.Companion.toString()" : 44,
    "kotlin.Companion_instance" : 54,
    "kotlin.Companion_getInstance()" : 171,
    "kotlin.Enum" : 1270,
    "kotlin.Enum.<init>(String, Int)" : 147,
    "kotlin.Enum.name" : 43,
    "kotlin.Enum.ordinal" : 43,
    "kotlin.Enum.compareTo(E)" : 452,
    "kotlin.Enum.compareTo(T)" : 318,
    "kotlin.Enum.toString()" : 133,
    "kotlin.toString()" : 375,
    "kotlin.Int__compareTo-impl(Int, Int)" : 150,
    "kotlin.Int__plus-impl(Int, Int)" : 154,
    "kotlin.Int__minus-impl(Int, Int)" : 155,
    "kotlin.Int__times-impl(Int, Int)" : 155,
    "kotlin.Int__div-impl(Int, Int)" : 400,
    "kotlin.Int__rem-impl(Int, Int)" : 185,
    "kotlin.Int__dec-impl(Int)" : 100,
    "kotlin.Int__rangeTo-impl(Int, Int)" : 125,
    "kotlin.Int__shl-impl(Int, Int)" : 153,
    "kotlin.Int__shr-impl(Int, Int)" : 155,
    "kotlin.Int__ushr-impl(Int, Int)" : 156,
    "kotlin.Int__and-impl(Int, Int)" : 150,
    "kotlin.Int__or-impl(Int, Int)" : 148,
    "kotlin.Int__xor-impl(Int, Int)" : 150,
    "kotlin.Int__toChar-impl(Int)" : 204,
    "kotlin.Int__toLong-impl(Int)" : 112,
    "kotlin.Int__toString-impl(Int)" : 122,
    "kotlin.Int__reinterpretAsChar-impl(Int)" : 132,
    "kotlin.Int" : 919,
    "kotlin.Int.<init>(Int)" : 95,
    "kotlin.Int.value" : 41,
    "kotlin.Int.compareTo(Int)" : 214,
    "kotlin.Int.compareTo(T)" : 287,
    "kotlin.Int.toString()" : 174,
    "kotlin.Long__compareTo-impl(Long, Long)" : 153,
    "kotlin.Long__plus-impl(Long, Long)" : 158,
    "kotlin.Long__minus-impl(Long, Long)" : 159,
    "kotlin.Long__times-impl(Long, Long)" : 159,
    "kotlin.Long__div-impl(Long, Long)" : 425,
    "kotlin.Long__rem-impl(Long, Long)" : 189,
    "kotlin.Long__rangeTo-impl(Long, Long)" : 130,
    "kotlin.Long__and-impl(Long, Long)" : 154,
    "kotlin.Long__xor-impl(Long, Long)" : 154,
    "kotlin.Long__toInt-impl(Long)" : 108,
    "kotlin.Long__toString-impl(Long)" : 124,
    "kotlin.Long" : 932,
    "kotlin.Long.<init>(Long)" : 96,
    "kotlin.Long.value" : 42,
    "kotlin.Long.compareTo(Long)" : 218,
    "kotlin.Long.compareTo(T)" : 289,
    "kotlin.Long.toString()" : 177,
    "kotlin.String" : 6307,
    "kotlin.String.<init>(String?, Int, WasmCharArray)" : 252,
    "kotlin.String.leftIfInSum" : 33,
    "kotlin.String.<get-length>()" : 134,
    "kotlin.String.length" : 42,
    "kotlin.String._chars" : 34,
    "kotlin.String.plus(Any?)" : 562,
    "kotlin.String.foldChars()" : 1913,
    "kotlin.String.compareTo(String)" : 2471,
    "kotlin.String.compareTo(T)" : 294,
    "kotlin.String.toString()" : 151,
    "kotlin.stringLiteral(Int, Int, Int)" : 585,
    "kotlin.Throwable" : 1279,
    "kotlin.Throwable.<init>(String?, Throwable?)" : 287,
    "kotlin.Throwable.<get-message>()" : 142,
    "kotlin.Throwable.message" : 47,
    "kotlin.Throwable.cause" : 48,
    "kotlin.Throwable.<init>(String?)" : 88,
    "kotlin.Throwable.<init>()" : 69,
    "kotlin.Throwable.jsStack" : 45,
    "kotlin.Throwable._stack" : 28,
    "kotlin.Throwable.suppressedExceptionsList" : 62,
    "kotlin.Throwable.toString()" : 371,
    "kotlin.captureStackTrace()" : 82,
    "kotlin.captureStackTrace__externalAdapter()" : 278,
    "kotlin.wasm.internal.isNotFirstWasmExportCall" : 73,
    "kotlin.wasm.internal.throwAsJsException(Throwable)" : 198,
    "kotlin.wasm.internal.throwJsError(JsString?, JsString?, JsAny)" : 335,
    "kotlin.wasm.internal.throwJsError__externalAdapter(String?, String?, JsAny)" : 601,
    "kotlin.wasm.internal._jsEmptyString" : 64,
    "kotlin.wasm.internal.jsToKotlinStringAdapter(JsAny)" : 2976,
    "kotlin.wasm.internal.stringLength(JsAny)" : 75,
    "kotlin.wasm.internal.jsExportStringToWasm(JsAny, Int, Int, Int)" : 454,
    "kotlin.wasm.internal.kotlinToJsStringAdapter(String?)" : 3533,
    "kotlin.wasm.internal.<get-jsEmptyString>()" : 337,
    "kotlin.wasm.internal.importStringFromWasm(Int, Int, JsAny?)" : 331,
    "kotlin.wasm.internal.importStringFromWasm__externalAdapter(Int, Int, JsAny?)" : 380,
    "kotlin.wasm.internal.getJsEmptyString()" : 66,
    "kotlin.wasm.internal.getJsEmptyString__externalAdapter()" : 279,
    "kotlin.wasm.internal.kotlinToJsAnyAdapter(Any?)" : 146,
    "kotlin.wasm.internal.anyToExternRef(Any)" : 217,
    "kotlin.wasm.internal.JsExternalBox" : 410,
    "kotlin.wasm.internal.JsExternalBox.<init>(JsAny)" : 125,
    "kotlin.wasm.internal.JsExternalBox.ref" : 41,
    "kotlin.wasm.internal.JsExternalBox.toString()" : 186,
    "kotlin.wasm.internal.asWasmExternRef()" : 149,
    "kotlin.wasm.internal.externrefToString(JsAny)" : 89,
    "kotlin.wasm.internal.externrefToString__externalAdapter(JsAny)" : 264,
    "kotlin.wasm.internal.jsCheckIsNullOrUndefinedAdapter(JsAny?)" : 459,
    "kotlin.wasm.internal.isNullish(JsAny?)" : 84,
    "kotlin.wasm.internal.jsToKotlinAnyAdapter(JsAny?)" : 154,
    "kotlin.wasm.internal.externRefToAny(JsAny)" : 257,
    "kotlin.wasm.internal.tryGetOrSetExternrefBox_$external_fun(JsAny, JsReference<JsExternalBox>)" : 174,
    "kotlin.wasm.internal.tryGetOrSetExternrefBox_$external_fun__externalAdapter(JsAny, JsReference<JsExternalBox>)" : 268,
    "kotlin.wasm.internal._K" : 39,
    "kotlin.wasm.internal._exp" : 41,
    "kotlin.wasm.internal._frc_minus" : 48,
    "kotlin.wasm.internal._frc_plus" : 47,
    "kotlin.wasm.internal._frc_pow" : 46,
    "kotlin.wasm.internal._exp_pow" : 45,
    "kotlin.wasm.internal.EXP_POWERS" : 60,
    "kotlin.wasm.internal.FRC_POWERS" : 59,
    "kotlin.wasm.internal.itoa32(Int, Int)" : 1758,
    "kotlin.wasm.internal.itoa64(Long, Int)" : 2471,
    "kotlin.wasm.internal.decimalCount32(Int)" : 1115,
    "kotlin.wasm.internal.utoaDecSimple(WasmCharArray, Int, Int)" : 914,
    "kotlin.wasm.internal.CharCodes_PLUS_instance" : 59,
    "kotlin.wasm.internal.CharCodes_MINUS_instance" : 60,
    "kotlin.wasm.internal.CharCodes_DOT_instance" : 58,
    "kotlin.wasm.internal.CharCodes__0_instance" : 57,
    "kotlin.wasm.internal.CharCodes_e_instance" : 56,
    "kotlin.wasm.internal.CharCodes_entriesInitialized" : 69,
    "kotlin.wasm.internal.CharCodes_initEntries()" : 529,
    "kotlin.wasm.internal.CharCodes" : 399,
    "kotlin.wasm.internal.CharCodes.<init>(String, Int, Int)" : 178,
    "kotlin.wasm.internal.CharCodes.code" : 40,
    "kotlin.wasm.internal.CharCodes.compareTo(CharCodes)" : 67,
    "kotlin.wasm.internal.CharCodes.toString()" : 44,
    "kotlin.wasm.internal.decimalCount64High(Long)" : 1214,
    "kotlin.wasm.internal.utoaDecSimple64(WasmCharArray, Long, Int)" : 1406,
    "kotlin.wasm.internal.digitToChar(Int)" : 275,
    "kotlin.wasm.internal.CharCodes_MINUS_getInstance()" : 111,
    "kotlin.wasm.internal.CharCodes__0_getInstance()" : 105,
    "kotlin.wasm.internal.properties initialized Number2String.kt" : 78,
    "kotlin.wasm.internal.<init properties Number2String.kt>()" : 15686,
    "kotlin.wasm.internal.stringPool" : 64,
    "kotlin.wasm.internal.unsafeRawMemoryToWasmCharArray(Int, Int, Int, WasmCharArray)" : 783,
    "kotlin.wasm.internal.consumeAnyIntoVoid(Any?)" : 115,
    "kotlin.wasm.internal.consumeIntIntoVoid(Int)" : 114,
    "kotlin.wasm.internal.unsafeWasmCharArrayToRawMemory(WasmCharArray, Int, Int, Int)" : 688,
    "kotlin.wasm.internal.rangeCheck(Int, Int)" : 214,
    "kotlin.wasm.internal.THROW_NPE()" : 70,
    "kotlin.wasm.internal.THROW_CCE()" : 68,
    "kotlin.wasm.internal.getPackageName(Int)" : 152,
    "kotlin.wasm.internal.getSimpleName(Int)" : 154,
    "kotlin.wasm.internal.getString(Int, Int, Int, Int)" : 453,
    "kotlin.wasm.internal.wasm_i32_compareTo(Int, Int)" : 229,
    "kotlin.wasm.internal.wasm_i64_compareTo(Long, Long)" : 231,
    "kotlin.collections.copyInto(CharArray, Int, Int, Int)" : 1127,
    "kotlin.collections.copyOf(Int)" : 114,
    "kotlin.collections.copyOfUninitializedElements(Int)" : 159,
    "kotlin.collections.copyOfUninitializedElements(Int, Int)" : 736,
    "kotlin.wasm.internal.WasmAnyArray" : 573,
    "kotlin.wasm.internal.WasmAnyArray.<init>(Int)" : 76,
    "kotlin.wasm.internal.WasmAnyArray.get(Int)" : 99,
    "kotlin.wasm.internal.WasmAnyArray.set(Int, Any?)" : 106,
    "kotlin.wasm.internal.WasmAnyArray.len()" : 88,
    "kotlin.wasm.internal.WasmAnyArray.toString()" : 44,
    "kotlin.wasm.internal.WasmCharArray" : 578,
    "kotlin.wasm.internal.WasmCharArray.<init>(Int)" : 76,
    "kotlin.wasm.internal.WasmCharArray.get(Int)" : 101,
    "kotlin.wasm.internal.WasmCharArray.set(Int, Char)" : 106,
    "kotlin.wasm.internal.WasmCharArray.len()" : 88,
    "kotlin.wasm.internal.WasmCharArray.toString()" : 44,
    "kotlin.wasm.internal.WasmShortArray" : 129,
    "kotlin.wasm.internal.WasmLongArray" : 127,
    "kotlin.assert(Boolean)" : 144,
    "kotlin.assert(Boolean, Function0<Any>)" : 232,
    "kotlin.assert$lambda" : 278,
    "kotlin.assert$lambda.<init>()" : 75,
    "kotlin.assert$lambda.invoke()" : 69,
    "kotlin.Comparator" : 86,
    "kotlin.Comparator.toString()" : 44,
    "kotlin.IllegalArgumentException" : 351,
    "kotlin.IllegalArgumentException.<init>(String?)" : 119,
    "kotlin.IllegalArgumentException.<get-message>()" : 50,
    "kotlin.IllegalArgumentException.toString()" : 44,
    "kotlin.IllegalArgumentException.<init>()[synthetic]" : 58,
    "kotlin.IndexOutOfBoundsException" : 448,
    "kotlin.IndexOutOfBoundsException.<init>()" : 87,
    "kotlin.IndexOutOfBoundsException.<init>(String?)" : 120,
    "kotlin.IndexOutOfBoundsException.<get-message>()" : 50,
    "kotlin.IndexOutOfBoundsException.toString()" : 44,
    "kotlin.IndexOutOfBoundsException.<init>()[synthetic]" : 58,
    "kotlin.AssertionError" : 722,
    "kotlin.AssertionError.<init>(Any?)" : 483,
    "kotlin.AssertionError.<get-message>()" : 50,
    "kotlin.AssertionError.toString()" : 44,
    "kotlin.AssertionError.<init>()[synthetic]" : 58,
    "kotlin.RuntimeException" : 400,
    "kotlin.RuntimeException.<init>()" : 71,
    "kotlin.RuntimeException.<init>(String?)" : 104,
    "kotlin.RuntimeException.<get-message>()" : 50,
    "kotlin.RuntimeException.toString()" : 44,
    "kotlin.RuntimeException.<init>()[synthetic]" : 58,
    "kotlin.Error" : 434,
    "kotlin.Error.<init>(String?)" : 93,
    "kotlin.Error.<init>(String?, Throwable?)" : 127,
    "kotlin.Error.<get-message>()" : 50,
    "kotlin.Error.toString()" : 44,
    "kotlin.Error.<init>()[synthetic]" : 58,
    "kotlin.Exception" : 379,
    "kotlin.Exception.<init>()" : 64,
    "kotlin.Exception.<init>(String?)" : 97,
    "kotlin.Exception.<get-message>()" : 50,
    "kotlin.Exception.toString()" : 44,
    "kotlin.Exception.<init>()[synthetic]" : 58,
    "kotlin.IllegalStateException" : 345,
    "kotlin.IllegalStateException.<init>(String?)" : 116,
    "kotlin.IllegalStateException.<get-message>()" : 50,
    "kotlin.IllegalStateException.toString()" : 44,
    "kotlin.IllegalStateException.<init>()[synthetic]" : 58,
    "kotlin.NullPointerException" : 310,
    "kotlin.NullPointerException.<init>()" : 82,
    "kotlin.NullPointerException.<get-message>()" : 50,
    "kotlin.NullPointerException.toString()" : 44,
    "kotlin.NullPointerException.<init>()[synthetic]" : 58,
    "kotlin.ClassCastException" : 306,
    "kotlin.ClassCastException.<init>()" : 80,
    "kotlin.ClassCastException.<get-message>()" : 50,
    "kotlin.ClassCastException.toString()" : 44,
    "kotlin.ClassCastException.<init>()[synthetic]" : 58,
    "kotlin.countLeadingZeroBits()" : 107,
    "kotlin.Function2" : 81,
    "kotlin.Function0" : 90,
    "kotlin.Function0.invoke()" : 35,
    "kotlin.io.Serializable" : 83,
    "kotlin.io.Serializable.toString()" : 44,
    "kotlin.js.toJsReference()" : 156,
    "kotlin.math.abs(Long)" : 278,
    "kotlin.random.defaultPlatformRandom()" : 88,
    "kotlin.random.initialSeed()" : 95,
    "kotlin.text.insertInt(CharArray, Int, Int)" : 327,
    "kotlin.text.unsafeStringFromCharArray(CharArray, Int, Int)" : 684,
    "kotlin.text.insertString(CharArray, Int, String, Int, Int)" : 1038,
    "kotlin.text.toString(Int)" : 2207,
    "kotlin.text.toString$getChar()" : 1129,
    "kotlin.text.STRING_CASE_INSENSITIVE_ORDER" : 87,
    "kotlin.text.concatToString(Int, Int)" : 1060,
    "kotlin.text.concatToString$default(Int?, Int?, Int, Any?)" : 905,
    "kotlin.text.sam$kotlin_Comparator$0" : 311,
    "kotlin.text.sam$kotlin_Comparator$0.function" : 61,
    "kotlin.text.sam$kotlin_Comparator$0.<init>(Function2<P1, P2, R>)" : 133,
    "kotlin.text.sam$kotlin_Comparator$0.toString()" : 44,
    "kotlin.text.STRING_CASE_INSENSITIVE_ORDER$lambda" : 226,
    "kotlin.text.STRING_CASE_INSENSITIVE_ORDER$lambda.<init>()" : 75,
    "kotlin.text.properties initialized StringsWasm.kt" : 76,
    "kotlin.text.<init properties StringsWasm.kt>()" : 541,
    "kotlin.wasm.unsafe.<Pointer__<init>-impl>(UInt)" : 135,
    "kotlin.wasm.unsafe.<Pointer__<get-address>-impl>(Pointer)" : 85,
    "kotlin.wasm.unsafe.Pointer__toString-impl(Pointer)" : 311,
    "kotlin.wasm.unsafe.Pointer" : 359,
    "kotlin.wasm.unsafe.Pointer.<init>(UInt)" : 91,
    "kotlin.wasm.unsafe.Pointer.address" : 44,
    "kotlin.wasm.unsafe.Pointer.toString()" : 160,
    "kotlin.wasm.unsafe.currentAllocator" : 79,
    "kotlin.wasm.unsafe.MemoryAllocator" : 225,
    "kotlin.wasm.unsafe.MemoryAllocator.<init>()" : 67,
    "kotlin.wasm.unsafe.MemoryAllocator.allocate(Int)" : 43,
    "kotlin.wasm.unsafe.MemoryAllocator.toString()" : 44,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator" : 6476,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.<init>(Int, ScopedMemoryAllocator?)" : 260,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.parent" : 43,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.destroyed" : 31,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.suspended" : 31,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.availableAddress" : 34,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.allocate(Int)" : 4766,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.createChild()" : 403,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.destroy()" : 383,
    "kotlin.wasm.unsafe.ScopedMemoryAllocator.toString()" : 44,
    "kotlin.wasm.unsafe.createAllocatorInTheNewScope()" : 653,
    "kotlin.wasm.unsafe.wasmMemorySize()" : 110,
    "kotlin.wasm.unsafe.wasmMemoryGrow(Int)" : 160,
    "kotlinx.browser.document_$external_prop_getter()" : 87,
    "kotlinx.browser.document_$external_prop_getter__externalAdapter()" : 299,
    "kotlinx.dom.appendText(String)" : 507,
    "org.w3c.dom.body_$external_prop_getter(Document)" : 105,
    "org.w3c.dom.body_$external_prop_getter__externalAdapter(Document)" : 172,
    "org.w3c.dom.createTextNode_$external_fun(Document, JsString?)" : 142,
    "org.w3c.dom.createTextNode_$external_fun__externalAdapter(Document, String)" : 375,
    "org.w3c.dom.ownerDocument_$external_prop_getter(Node)" : 119,
    "org.w3c.dom.ownerDocument_$external_prop_getter__externalAdapter(Node)" : 183,
    "org.w3c.dom.appendChild_$external_fun(Node, Node)" : 127,
    "org.w3c.dom.appendChild_$external_fun__externalAdapter(Node, Node)" : 334,
    "main()" : 1130,
    "greet()" : 51,
    "kotlin.wasm.internal.fieldInit()" : 172,
    "kotlin.wasm.internal.mainCallsWrapper()" : 37
};
